const FETCHREPOS = "FORM/FETCHAPI";
const KEYLANGUAGE = "FORM/KEYLANGUAGE";
const TOGGLEVIEW = "FORM/TOGGLEVIEW";
const FAVORITE = "FAVORITE";
const DELETEFAVORITE = "DELETEFAVORITE"

export {
  FETCHREPOS,
  KEYLANGUAGE,
  TOGGLEVIEW,
  FAVORITE,
  DELETEFAVORITE
}